jenkins

diff --git a/80-cdn/Jenkinsfile b/80-cdn/Jenkinsfile
--- a/80-cdn/Jenkinsfile
+++ b/80-cdn/Jenkinsfile
@@ -1,13 +1,15 @@
 pipeline {
     agent {
-        label 'agent-1'
+        label 'AGENT-1'
     }
     options{
         timeout(time: 30, unit: 'MINUTES')
         disableConcurrentBuilds()
         ansiColor('xterm')
     }
-    
+    // environment {
+    //     DEBUG = 'true'
+    // }
 
     parameters {
         choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select Action')
@@ -37,16 +39,33 @@ pipeline {
                         if [ ${params.ACTION} == 'apply' ]
                         then
                             terraform apply -auto-approve tfplan
-                        elif [ ${params.ACTION} == 'destroy' ]
-                        then
-                            terraform destroy -auto-approve
                         fi
                     """
                 }
             }
         }
-
-        stage('Parallel-1') {
+        stage('Destroy'){
+            when {
+                expression { params.ACTION == 'destroy' }
+            }
+            steps{
+                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
+                    script {
+                        def directories = ['80-cdn', '70-ecr', '60-alb', '50-acm', '40-eks', '30-rds', '20-bastion', '10-sg', '00-vpc']
+                        for (dir in directories) {
+                            echo "Destroying resources in directory: ${dir}"
+                            sh """
+                            cd ${dir}
+                            terraform init -reconfigure
+                            terraform destroy -auto-approve || { echo "Failed to destroy resources in ${dir}"; exit 1; }
+                            cd ..
+                            """
+                        }
+                    }
+                }
+            }
+        }
+        /* stage('Destroy') {
             when {
                 expression { params.ACTION == 'destroy' }
             }
@@ -56,19 +75,14 @@ pipeline {
                         build job: '70-ecr', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
                     }
                 }
-                stage('Alb') {
+                stage('ALB') {
                     steps {
                         build job: '60-alb', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
                     }
                 }
-                stage('Acm') {
+                stage('EKS') {
                     steps {
-                        build job: '50-acm', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
-                    }
-                }
-                stage('Eks') {
-                    steps {
-                        build job: '40-eks', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
+                        build job: '40-eks', parameters: [string(name: 'ACTION', value: "destroy")], wait: true
                     }
                 }
                 stage('Bastion') {
@@ -78,17 +92,33 @@ pipeline {
                 }
 
             }
-        }
-        stage('SG-Destroy'){
-            steps {
-                build job: '10-sg', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
+        } */
+        
+        /* stage('Sequential') {
+            when {
+                expression { params.ACTION == 'destroy' }
             }
-        }
-        stage('VPC-Destroy'){
-            steps {
-                build job: '00-vpc', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
+            stages {
+                
+                stage('ACM') {
+                    steps {
+                        build job: '50-acm', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
+                    }
+                }
+                stage('SG-Destroy'){
+                    steps {
+                        build job: '10-sg', parameters: [string(name: 'ACTION', value: "destroy")], wait: true
+                    }
+                }
+                stage('VPC-Destroy'){
+                    steps {
+                        build job: '00-vpc', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
+                    }
+                }
             }
-        }
+                
+        } */
+        
     }
 
     post {
